# Generated by Django 2.2.9 on 2020-02-07 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200206_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='virus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='virus_resource',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='access_key',
            field=models.CharField(max_length=150),
        ),
    ]
