# Generated by Django 2.2.9 on 2020-02-11 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200208_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainClientInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 2, 11, 1, 49, 49, 655940, tzinfo=utc))),
                ('modified', models.DateTimeField(default=datetime.datetime(2020, 2, 11, 1, 49, 49, 655940, tzinfo=utc))),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('client_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ClientInfo')),
            ],
        ),
    ]
