# Generated by Django 2.2.9 on 2020-02-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200207_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='scan_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='virus_resource',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
