# Generated by Django 2.2.9 on 2020-02-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200207_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='virus_resource',
            new_name='virusscan_resource',
        ),
    ]
